language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python urlExtractor.py demo.xls

notifications:
  slack: stoooges-team:xrWuw1yjkLNpZqDtdqyade3E